version: '3.9'

services:  
  redis:
    image: redis
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  storage_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

